### ISSUE TITLE
Create wireframe of UI using Figma

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/internbit#2]
To provide a bit more insight into InternBit, create a mockup user interface using [Figma](https://figma.com).   There are some steps to follow so that we can collaborate on these mockups:

1. Create an account in figma using your hawaii.edu email address.
2. Request educational status. See [https://www.figma.com/pricing-faq/#is-figma-free-for-students](https://www.figma.com/pricing-faq/#is-figma-free-for-students) for details.
3. Once your account is verified as educational (it only takes a couple of minutes--they send an email to your hawaii.edu account and you have to reply to it), then let @philipmjohnson know.
4. Philip will then "invite" you to the RadGrad project team.  At that point, you can start creating mockups that everyone on the RadGrad team can see and collaborate on. 

When you are finished creating around a half dozen UI mockups, post a summary as a comment to this issue.

**Comment by kellikt** [comment]
I created six different layout mockups for Figma, but learned a lot along the way! For my first mockup, I got really caught up in finding a nice color palette to work with (as well as learning how to use the app in general), so I spent a lot of time mainly focusing on the design aspect of the mockup. 

For the other mockups, I focused heavily on the layout/the placement of the elements of the interface, such as how users would see the data pulled from RadGrad/how they would edit their data. I mainly created mockups for the student UI / company UI, although I do have a few mockups for a homepage/internship overview page. 

For Mockups 2 and 3, I tried to envision how we could implement the data pulled/inputted as graphs - as either pie charts or bar graphs. These mockups focused on possible ways to make the data easily readable and understandable.

For Mockups 4 and 5, I tried to visualize if users might like to see a sample of recommendations based on their data, before enabling InternBit to provide internship recommendations. I mainly experimented with different ways to present the recommendations without cluttering the interface.

Mockup 6 was a bit more experimental, as I wanted to see how the interface would look if I spaced out some of the data instead of placing most of it on one page. I felt that this design gave a little more room for users, making the data presented less overwhelming.

**Comment by auusui** [comment]
Completed my 6 mockups:

Mockup1:  I tried to make it vibrant so it would pop out and be appealing to the eye.  The landing page shows how the system works by using an informational approach.  I put in pictures to make it more visual and fun.  The profile page has a side menu: the profile, skills/experience, favorites, tips, recommendations.  They can add/edit/remove skill or experience cards as they progress through the school years.  Their recommended page is the ones the system picks out that best fits them.  The tips page is helpful links to articles or essays that may answer FAQ among undergraduate students.  The home page I wanted to look interactive so it has a cool design that looks fun and colorful.  

Mockup2: I wasn't sure if we were only supposed to do web frames so I tried out an iPhone 11 pro frame.  I wanted it to be simple and concise because of the space limit as well as the attention span one has while on a phone.  The landing page explains what the app does.  The home page is simple and self-explanatory for the user to pick what page they'd like to visit.  The profile button leads to a different page that has a dropdown menu for the user.  It is their own resume and webspace basically.  Same actions as mockup 1. 

Mockup3: I tried to make it less cluttered because I wanted the user to not be overwhelmed with a ton of reading.  The landing page is made of statistics that I made up but can research about it to make it valid.  I thought a factual approach would pull a reader in than a summary of what it's about.  Then the home page tells the user how to use the app.  There is also a company UI that they can add internships onto the database.  The student UI includes all the stuff the system needs to find the best recommendations: skill, experience, major, year, resume, etc.  

Mockup4:  This was for an iPad Pro.  I wanted to experiment with different frames.  I wanted to take a different design approach than the previous mockups.  So I changed up the home page and profile page.  The landing page is an animation drawing of a chart representing stairs as a metaphor.  Supposed to be motivational.  This one makes the user fill out a questionnaire then the database will search internships.  Once it is done, it gives a list of the top 4 and the user can choose to toggle it, and then it will show the next 5.

Mockup5: This one I wanted to make a uniform and simple design just because sometimes less is more.  I made it a progression type of page.  Once the user does step 1, then it gets checked off and on to the next step.  This way, no one will get lost.  The profile page is like their own webspace as well.  They have 3 buttons to take them to the recommendations list, explore page, and the favorites page where they saved internships they search for.  They also fill out the profile questions.  

Mockup6: I wanted to make this one a modern-looking design with some organization.  The internship page with the recommendations has its own page so the user may browse other options as well with filters.  The profile page holds their skills, experience, and interests.  That's what will be used to find the internship.

**Comment by jhsuP** [comment]
I completed 5 mockups:

[Version #1](https://www.figma.com/file/zidqFwZ0wyJ8ZWp6qtiBwe/Version-%231): I wasn't sure if we were only supposed to create the student/company UI. This version provides a layout for all parts of the site from a student's profile to internship listings. There are comments on the mock-up that provide information about how each page functions. In this version, I took into account the points a student will be able to earn from RadGrad and integrated it into all/recommended internships.

[Version #2](https://www.figma.com/file/pkTspn8u0xS78ITgzes9Xv/Version-%232) For this version, I read Mirabela's research proposal where she mentioned: "This profile page could also show them the progress they are at to fulfilling all the skills required for one of the career goals they selected". Hence, I decided to integrate it into the profile page. For each career goal, it shows all the recommended skills and their progress (purple means completed, gray means not fulfilled yet).

[Version #3](https://www.figma.com/file/zuQZ638i83A2t39NwZAvYW/Version-%233): I thought that displaying the progress as a bar with a percentage, whereupon clicking them, it shows them a full detail of the courses they need to take. In this version, I also decided to show "recommended opportunities" which will be read from RadGrad. Extra-curricular activities along with classes are one of the best ways to learn so I felt that incorporating it on the profile page will help the student realize what are the "steps" needed to fulfill their career goal. I decided to go for a flat and simple look as I felt it would look more clean and appealing. 

[Version #4](https://www.figma.com/file/bfBQQ9b2hes5npB3f72UyQ/Version-%234?node-id=0%3A1): This version also incorporates a progress bar. However, it also has an overall progress, which takes the collective percentage (eg. percentage of web development progress, software engineer, etc...).

[Version #5](https://www.figma.com/file/nzRoODk8zxuQ7M6DTHvXHe/Version-%235): I mainly played around with the layout for this case. I tried to go for a more "modern" appeal but to be honest, this isn't exactly a favorite. 

For all of these, I was focused on tying to make the layout and theme look pretty which took up most of my time. Next time, I should just keep to the basics and work more on the layout instead of the coloring, which could come after.
