### ISSUE TITLE
Create stackoverflow.canonical.data.json

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/internbit#27]
See: https://stackoverflow.com/jobs

**Comment by jhsuP** [comment]
[Code](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/stackoverflow.js) | [Data](https://github.com/radgrad/internbit-scraper-jh-puppeteer/blob/master/data/canonical/stackoverflow.canonical.data.json)

**Comment by philipmjohnson** [comment]
I just looked at https://stackoverflow.com/jobs?q=internship and it seems like it has more jobs than the scraper is picking up. Could someone check this out?

**Comment by jhsuP** [comment]
Right now it filters based on the "internship" tag- 
![image](https://user-images.githubusercontent.com/56209781/96061798-d2ee0c80-0e2f-11eb-94c4-c38afefb6175.png)
![image](https://user-images.githubusercontent.com/56209781/96061809-dc777480-0e2f-11eb-83c4-178e0079a273.png)

Hence it misses others because their job type is something different, for example: 
![image](https://user-images.githubusercontent.com/56209781/96061843-f022db00-0e2f-11eb-967d-e47e6ace734f.png)

Will remove the filter so a wider range can be picked up.
