### ISSUE TITLE
Add a remote field.

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/internbit#49]
Please do work for this in branch issue-49

Make "remote" a top-level field. 

If the remote field is missing, then remote is false.

If the remote field is present and the value is true, then the internship is remote.

**Comment by jhsuP** [comment]
Implemented the ability to filter by remote. Allows the user to hone in on specific locations (Eg. Remote internships in CA)
![image](https://user-images.githubusercontent.com/56209781/95156534-7ce3df80-0732-11eb-9eae-d9769be19844.png)

During post-scraping where we parse all the internships, we check to see if it's remote:

```javascript
    // if there is no remote section
    try {
      if (!text[i].remote) {
        let remote = false;
        if (isRemote(text[i].position) || isRemote(text[i].description)
            || isRemote(text[i].location.city) || isRemote(text[i].location.state)) {
          remote = true;
        }
        text[i].remote = remote;
      }
    } catch (e) {
      text[i].remote = false;
    }
```

The function is located under ``scraperFunctions.js`` so it can also be used during the scraping process as well.
```javascript
/**
 * Checks to see if the data contains the word 'remote'
 * @param data String The data we're checking
 * @returns boolean true if found, else false
 */
function isRemote(data) {
  const parsed = data.replace(/([\[\]()-])gmi/, '').toLowerCase();
  if (parsed.includes('remote')) {
    return true;
  }
  return false;
}
```

We also check for location:
```javascript
    // if text has no location.state or it is empty
    if (!text[i].location.state || text[i].location.state === '') {

      text[i].location.state = 'Out of Country';

      // Check to see if it's USA
      for (let k = 0; k < cities.length; k++) {
        if (text[i].location.city.includes(cities[k].City) || text[i].location.city.includes(cities[k].State)) {
          text[i].location.state = 'United States';
        }
      }
```
This addresses issue #38 where angellist's location varies. 
Eg. New York City • San Francisco • London • Remote 

At the moment if any of the locations listed correspond to a city/state in US, the state is set to 'United States' as a catch all.
![image](https://user-images.githubusercontent.com/56209781/95156821-2cb94d00-0733-11eb-9fff-36cb3a57767a.png)

Otherwise, they're labeled as "Out of Country".
![image](https://user-images.githubusercontent.com/56209781/95157156-f0d2b780-0733-11eb-8df1-63600cb52521.png)

It is important to note that cities.json contains only the "popular" cities so in the future we may need to add additional US cities for those that aren't covered.
