### ISSUE TITLE
Decide between Osmosis and X-Ray

### ISSUE THREAD

**Issue by philipmjohnson** [radgrad/internbit#9]
Compare code and functionality, make recommendation.

**Comment by jhsuP** [comment]
X-Ray 

Pros: 
- Easy to read 
- A lot of built-in functions (eg. write to file)
- Simple 
- Has different drivers (eg. Phantom.js, nightmare...)

For example, the code below scapes all of simplyHired:
```javascript
 const Xray = require('x-ray');
 const x = Xray();

 x('https://www.simplyhired.com/search/Software-Development-and-Architecture-Occupations/category/47887de2-45aa-4327-9499-7fdba46c5e0f?sb=dd&jt=internship&job=Zs7Qu-vSCX-UxpXNs6tCVGSsrCms1zmSHtpZ_ujWFskCxymqi53oaA', '.SerpJob-jobCard.card', [{
   position: 'h2',
   link: 'a@href',
   company: '.jobposting-company',
   location: 'span.jobposting-location',
   description: 'p',
   posted: 'time',
   education: x('a@href', '.viewjob-content ul:first-of-type '),
 }]).paginate('.next-pagination a@href')
     .write('simplyHiredResults.json');
}
```

Cons: 
- Has no infinite scroll 
- Unable to interact with the website (Eg. click buttons for filters)
- Not a lot of documentation on how the drivers work. (Personally I spent over 10+ hours trying to get phantom driver to work without any results).

Overall, I think Osmosis and X-ray both are the same, but I think X-ray is a little better as it has a built-in write function.

**Comment by kellikt** [comment]
Pros of Osmosis:

- Compact, relatively lightweight
- Scrapes more quickly than Puppeteer
- Built-in functions to follow links, create objects based on the data scraped, find elements by selector, handle pagination, and scrape data from each element (instead of using a for loop)

Cons of Osmosis:

- No built-in write function (X-Ray has this)
- No built-in way to handle infinite scroll (Puppeteer can handle this)
- No built-in way to log into pages (Puppeteer can handle this)
- Syntax of X-Ray is more condensed, slightly more intuitive than Osmosis (ex. Scraping multiple results can be done in one function, Osmosis requires two calls to separate functions)

Conclusion: Osmosis and X-Ray are relatively similar, but X-Ray appears to be an improvement in a few areas, such as the more readable/intuitive syntax and built-in write function. X-Ray seems to be the better option for simple web-scraping.

**Comment by philipmjohnson** [comment]
But consider Cheerio for better pagination support (i.e. Indeed)
